# Site settings
title: mHACKeroni
email: mhackeroni@gmail.com
baseurl: ""
url: "http://mhackeroni.it"
description: mHACKeroni team website
github: https://github.com/mhackeroni

author:
  name     : 'mHACKeroni'
  email    : mhackeroni@gmail.com
  url      : http://mhackeroni.it
  twitter  : https://twitter.com/mhackeroni

paginate: 4
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
