title: mHACKeroni
logo: /assets/img/logo.png
twitter_logo: /assets/img/twitter.png
gmail_logo: /assets/img/gmail.png
github_logo: /assets/img/github.png
author:
    name: mHACKeroni
    mail: mhackeroni@gmail.com
    github: https://github.com/mhackeroni

disqus_account: mhackeroni

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
paginate: 10
highlighter: rouge
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: ""
    values:
      type: "posts"
      layout: "post"
